### PR TITLE
Update to base/Buffer 0.8.7 part 2

### PR DESCRIPTION
**Pull request by f0i**
This is the 2nd part to port new functions from base/Buffer.

- :one: <- functions already added in #11 
- [x] <- functions added in this PR
- [ ]  <- functions that will be added in further PRs

# Buffer functions

- :one: initPresized
- :one: init
- :one: size
- :one: add
- :one: get
- :one: getOpt
- :one: put
- :one: removeLast
- :one: remove
- :one: clear
- [x] filterEntries
- :one: capacity
- :one: reserve
- :one: append
- [x] insert
- [x] insertBuffer
- [x] sort
- :one: vals
- [x] isEmpty
- :one: contains
- :one: clone
- [x] max
- [x] min
- [x] equal
- [x] compare
- [x] toText
- [x] hash
- :one: indexOf
- [ ] lastIndexOf
- [ ] indexOfBuffer
- [ ] binarySearch
- [ ] subBuffer
- [ ] isSubBufferOf
- [ ] isStrictSubBufferOf
- [ ] prefix
- [ ] isPrefixOf
- [ ] isStrictPrefixOf
- [ ] suffix
- [ ] isSuffixOf
- [ ] isStrictSuffixOf
- [ ] forAll
- [ ] forSome
- [ ] forNone
- :one: toArray
- :one: toVarArray
- :one: fromArray
- [ ] fromVarArray
- [ ] fromIter
- [ ] trimToSize
- [ ] map
- [ ] iterate
- [ ] mapEntries
- [ ] mapFilter
- [ ] mapResult
- [ ] chain
- [ ] foldLeft
- [ ] foldRight
- [ ] first
- [ ] last
- [ ] make
- [ ] reverse
- [ ] merge
- [ ] removeDuplicates
- [ ] partition
- [ ] split
- [ ] chunk
- [ ] groupBy
- [ ] flatten
- [ ] zip
- [ ] zipWith
- [ ] takeWhile
- [ ] dropWhile

### CODE REVIEW

**Review by ByronBecker — APPROVED** [review]
Looks great, merging in. I don't see any issues from my side, but would love it if you could add a PR directly taking the test cases from here https://github.com/dfinity/motoko-base/blob/master/test/Buffer.test.mo

**Comment by f0i** [comment]
Great!
I created [a branch with the updated test cases](https://github.com/f0i/StableBuffer/commits/update_tests_to_base_0.8.7_part3). I was planning to split it into 3 parts:

1. Adding the `Buffer.test.mo` as is, and updating to a current compiler version to support the syntax of some tests.
2. Replace Buffer with StableBuffer in  `Buffer.test.mo` and update all test cases accordingly.
3. Rename the file from `Buffer.test.mo` to `StableBuffer.test.mo`, remove the old test and use the new test from the Makefile.

It's a big file but it's probably faster to compare the diff between Buffer.test and StableBuffer.test then gradually adding the test cases.

**Comment by ByronBecker** [comment]
> It's a big file but it's probably faster to compare the diff between Buffer.test and StableBuffer.test then gradually adding the test cases.

Definitely!

I'll review the rest of the PRs (part 3-x) next, can you resolve the merge conflict?

**Comment by f0i** [comment]
Just resolved the merge conflict. Sorry, somehow missed it before

**Pull request merged**
